// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using classroom.Data;

#nullable disable

namespace classroom.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("classroom.Models.Clase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aula")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Aula");

                    b.Property<string>("CodigoAcceso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CodigoAcceso");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Color");

                    b.Property<string>("Curso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Curso");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Nombre");

                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer")
                        .HasColumnName("UsuariosId");

                    b.HasKey("Id");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Clases", (string)null);
                });

            modelBuilder.Entity("classroom.Models.Entrega", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("archivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("archivo");

                    b.Property<string>("archivoMimeType")
                        .HasColumnType("text")
                        .HasColumnName("archivoMimeType");

                    b.Property<string>("archivoNombreOriginal")
                        .HasColumnType("text")
                        .HasColumnName("archivoNombreOriginal");

                    b.Property<long?>("archivoSize")
                        .HasColumnType("bigint")
                        .HasColumnName("archivoSize");

                    b.Property<string>("asunto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asunto");

                    b.Property<bool>("entregada")
                        .HasColumnType("boolean")
                        .HasColumnName("entregada");

                    b.Property<DateTime?>("fecha_entrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("idusuario")
                        .HasColumnType("integer")
                        .HasColumnName("idusuario");

                    b.Property<decimal?>("nota")
                        .HasColumnType("numeric")
                        .HasColumnName("nota");

                    b.Property<int>("publicacionId")
                        .HasColumnType("integer")
                        .HasColumnName("publicacionId");

                    b.HasKey("id");

                    b.HasIndex("idusuario");

                    b.HasIndex("publicacionId");

                    b.ToTable("Entregas", (string)null);
                });

            modelBuilder.Entity("classroom.Models.PadreAlumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("Activo");

                    b.Property<int>("AlumnoId")
                        .HasColumnType("integer")
                        .HasColumnName("AlumnoId");

                    b.Property<DateTime>("FechaVinculo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("FechaVinculo");

                    b.Property<int>("PadreId")
                        .HasColumnType("integer")
                        .HasColumnName("PadreId");

                    b.HasKey("Id");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("PadreId", "AlumnoId")
                        .IsUnique();

                    b.ToTable("PadreAlumno", (string)null);
                });

            modelBuilder.Entity("classroom.Models.Publicacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AutorId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Puntuacion")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.HasIndex("ClaseId");

                    b.ToTable("Publicaciones", (string)null);
                });

            modelBuilder.Entity("classroom.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("codigoAlumno")
                        .HasColumnType("text")
                        .HasColumnName("codigoAlumno");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("fotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("fotoUrl");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<int>("rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("classroom.Models.UsuarioClase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaseId")
                        .HasColumnType("integer")
                        .HasColumnName("claseId");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuarioId");

                    b.HasKey("Id");

                    b.HasIndex("ClaseId");

                    b.HasIndex("UsuarioId", "ClaseId")
                        .IsUnique();

                    b.ToTable("UsuarioClase", (string)null);
                });

            modelBuilder.Entity("classroom.Models.Clase", b =>
                {
                    b.HasOne("classroom.Models.Usuario", "ProfesorCreador")
                        .WithMany("ClasesCreadas")
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProfesorCreador");
                });

            modelBuilder.Entity("classroom.Models.Entrega", b =>
                {
                    b.HasOne("classroom.Models.Usuario", "Usuario")
                        .WithMany("Entregas")
                        .HasForeignKey("idusuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("classroom.Models.Publicacion", "Publicacion")
                        .WithMany("Entregas")
                        .HasForeignKey("publicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("classroom.Models.PadreAlumno", b =>
                {
                    b.HasOne("classroom.Models.Usuario", "Alumno")
                        .WithMany("Padres")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("classroom.Models.Usuario", "Padre")
                        .WithMany("Hijos")
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("classroom.Models.Publicacion", b =>
                {
                    b.HasOne("classroom.Models.Usuario", "Autor")
                        .WithMany("Publicaciones")
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("classroom.Models.Clase", "Clase")
                        .WithMany("Publicaciones")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Clase");
                });

            modelBuilder.Entity("classroom.Models.UsuarioClase", b =>
                {
                    b.HasOne("classroom.Models.Clase", "Clase")
                        .WithMany("UsuarioClases")
                        .HasForeignKey("ClaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("classroom.Models.Usuario", "Usuario")
                        .WithMany("UsuarioClases")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clase");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("classroom.Models.Clase", b =>
                {
                    b.Navigation("Publicaciones");

                    b.Navigation("UsuarioClases");
                });

            modelBuilder.Entity("classroom.Models.Publicacion", b =>
                {
                    b.Navigation("Entregas");
                });

            modelBuilder.Entity("classroom.Models.Usuario", b =>
                {
                    b.Navigation("ClasesCreadas");

                    b.Navigation("Entregas");

                    b.Navigation("Hijos");

                    b.Navigation("Padres");

                    b.Navigation("Publicaciones");

                    b.Navigation("UsuarioClases");
                });
#pragma warning restore 612, 618
        }
    }
}
